spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true


gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}